apiVersion: v1
kind: ServiceAccount
metadata:
  name: dapr-client
  namespace: azure-iot-operations
  annotations:
    aio-mq-broker-auth/group: dapr-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-vdb-dapr-workload
  namespace: azure-iot-operations
  # labels:
  #   app: rag-vdb-dapr-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-vdb-dapr-workload
  template:
    metadata:
      labels:
        app: rag-vdb-dapr-workload
      annotations:
        dapr.io/enabled: "true"
        dapr.io/inject-pluggable-components: "true"
        dapr.io/app-id: "rag-vdb-dapr-workload"
        dapr.io/app-port: "8602"
        dapr.io/app-protocol: "http"
        dapr.io/log-level: "debug"
        dapr.io/sidecar-liveness-probe-delay-seconds: "10"
        dapr.io/sidecar-liveness-probe-timeout-seconds: "5"
        dapr.io/sidecar-readiness-probe-delay-seconds: "10"
        dapr.io/sidecar-readiness-probe-timeout-seconds: "5"

    spec:
      serviceAccountName: dapr-client
      #serviceAccountName: rag-interface-mqtt-client
      volumes:
      # SAT used to authenticate between Dapr and the MQTT broker
      - name: mqtt-client-token
        projected:
          sources:
            - serviceAccountToken:
                path: mqtt-client-token
                audience: aio-mq
                expirationSeconds: 86400

      # Certificate chain for Dapr to validate the MQTT broker
      - name: aio-ca-trust-bundle
        configMap:
          name: aio-ca-trust-bundle-test-only

      containers:
        - name: rag-vdb
          image: airstream.azurecr.io/rag-on-edge-vectordb:latest
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: rag-vdb-service
  namespace: azure-iot-operations
  labels:
    app: rag-vdb-dapr-workload
spec:
  selector:
    app: rag-vdb-dapr-workload
  ports:
    - protocol: TCP
      port: 8602
      targetPort: 8602
  type: LoadBalancer
